name: Deploy Angular App (ETMS-FE)

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to the main branch

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.22.12  # Adjust Node version if needed

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/etms-fe  # Change to match your Angular app build path

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist/

      # Option 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: etms-fe/dist/etms-fe  # Updated to your project name
          token: ${{ secrets.MY_SECRET }}

      # Option 2: Deploy to Firebase Hosting (Uncomment to use)
      # - name: Deploy to Firebase
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: ${{ secrets.GITHUB_TOKEN }}
      #     firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #     projectId: your-firebase-project-id

      # Option 3: Deploy to Remote Server via SSH (Uncomment to use)
      # - name: Deploy to Remote Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     source: "dist/etms-fe/*"
      #     target: "/var/www/html/etms-fe"
